###############

GPU: [0]

VERBOSE: True

MODEL:
  MODE: 'Demosaicing'
  SESSION: 'Unet_Ada_Res'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 8
  NUM_EPOCHS: 100
  LR_INITIAL: 1e-4
  #NEPOCH_DECAY: [40]
  #BETA1: 0.9

TRAINING:
  TRAIN_PS: 128
  VAL_PS: 196
  RESUME: False
  TRAIN_DIR: ''   # path to training data
  VAL_DIR: ''     # path to validation data
  SAVE_DIR: './checkpoints'          # path to save models and images
  SAVE_IMAGES: True
  #VAL_AFTER_EVERY: 1
